name: Deploy BookStore-Frontend (GitHub Repository Name)

on: 
  push:
    branches:
      - master (Branch where this repository is pushed previously)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sushantbagul/bookstore_frontend  . (Dockerhub Username/Repository Name . )


      - name: Publish Image to docker hub
        run: docker push sushantbagul/bookstore_frontend:latest (DockerHub Username/Repository Name:latest )
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull sushantbagul/bookstore_frontend:latest (DockerHub Username/Repository Name:latest )
      - name: Delete old container
        run: docker rm -f bookstore-frontend-container (Old Container Name if any/New container Name)
      - name: Run Docker Container
        run: docker run -d -p 5173:80(Configured/Default Port:Configured/Default Port) --name bookstore-frontend-container (New Container Name) sushantbagul/bookstore_frontend (DockerHub Username/Repository Name)
